-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.a123
(
    name character varying(50) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.b234
(
    name1 character varying(55) COLLATE pg_catalog."default",
    name2 character varying(50) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.congregation
(
    cong_id integer NOT NULL,
    cong_dist_id integer,
    cong_sek_id integer,
    cong_par_id integer,
    cong_code character(4) COLLATE pg_catalog."default",
    cong_name character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT congregation_pkey PRIMARY KEY (cong_id)
);

CREATE TABLE IF NOT EXISTS public.elc_seket
(
    sek_id integer NOT NULL,
    dist_id integer,
    sek_code character(3) COLLATE pg_catalog."default",
    sek_name character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT pk_tbl_sek PRIMARY KEY (sek_id)
);

CREATE TABLE IF NOT EXISTS public.my_names
(
    order_id integer,
    title character varying(40) COLLATE pg_catalog."default",
    name character varying(60) COLLATE pg_catalog."default",
    surname character varying(45) COLLATE pg_catalog."default",
    status numeric(3, 0),
    surname2 character varying(25) COLLATE pg_catalog."default",
    number2 numeric(3, 0)
);

CREATE TABLE IF NOT EXISTS public.tbl_admin_struc1
(
    admin_id integer NOT NULL,
    admin_province character varying(25) COLLATE pg_catalog."default",
    admin_district character varying(30) COLLATE pg_catalog."default",
    admin_llg character varying(35) COLLATE pg_catalog."default",
    admin_ward character varying(15) COLLATE pg_catalog."default",
    admin_village character varying(25) COLLATE pg_catalog."default",
    admin_tribe character varying(25) COLLATE pg_catalog."default",
    admin_clan character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT tbl_admin_struc1_pkey PRIMARY KEY (admin_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_admin_structure
(
    admin_province character varying(40) COLLATE pg_catalog."default" NOT NULL,
    admin_district character varying(40) COLLATE pg_catalog."default" NOT NULL,
    admin_llg character varying(40) COLLATE pg_catalog."default" NOT NULL,
    admin_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT admin_structure_pkey PRIMARY KEY (admin_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_banking
(
    ba_pers_id integer NOT NULL,
    ba_bank character varying(30) COLLATE pg_catalog."default",
    ba_account_name character varying(30) COLLATE pg_catalog."default",
    ba_account_nr numeric(15, 0),
    ba_nas_fund numeric(15, 0),
    ba_eda_supa numeric(15, 0),
    ba_other character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT tbl_banking_pkey PRIMARY KEY (ba_pers_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_dep_pers_rel
(
    rel_pers_id integer NOT NULL,
    rel_dep_id integer NOT NULL,
    rel_order integer NOT NULL,
    CONSTRAINT tbl_dep_pers_rel_pkey PRIMARY KEY (rel_pers_id, rel_dep_id, rel_order)
);

CREATE TABLE IF NOT EXISTS public.tbl_dependants
(
    dep_id integer NOT NULL,
    dep_name character varying(25) COLLATE pg_catalog."default",
    dep_sex character(1) COLLATE pg_catalog."default",
    dep_dob character varying(15) COLLATE pg_catalog."default",
    dep_relation character varying(15) COLLATE pg_catalog."default",
    dep_disability character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT "Dependants_pkey" PRIMARY KEY (dep_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_edu_other
(
    eo_id integer NOT NULL,
    eo_order integer NOT NULL,
    eo_name character varying(110) COLLATE pg_catalog."default",
    eo_duration character varying(15) COLLATE pg_catalog."default",
    eo_start_end character varying(20) COLLATE pg_catalog."default",
    eo_trainer_institution character varying(110) COLLATE pg_catalog."default",
    eo_sttainment character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT tbl_edu_other_pkey PRIMARY KEY (eo_order, eo_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_edu_school
(
    es_id integer NOT NULL,
    es_order integer NOT NULL,
    es_school_name character varying(40) COLLATE pg_catalog."default",
    es_level character varying(30) COLLATE pg_catalog."default",
    es_year_graduated character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT tbl_edu_school_pkey PRIMARY KEY (es_id, es_order)
);

CREATE TABLE IF NOT EXISTS public.tbl_edu_tertiary
(
    et_id integer NOT NULL,
    et_order integer NOT NULL,
    et_institution character varying(40) COLLATE pg_catalog."default",
    et_course character varying(80) COLLATE pg_catalog."default",
    et_years character varying(20) COLLATE pg_catalog."default",
    et_year_graduated numeric(4, 0),
    et_attainment character varying(80) COLLATE pg_catalog."default",
    CONSTRAINT tbl_edu_tertiary_pkey PRIMARY KEY (et_order, et_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_elc_cong_codes
(
    cong_id integer NOT NULL,
    cong_dist_code character(3) COLLATE pg_catalog."default",
    cong_dist_name character varying(35) COLLATE pg_catalog."default",
    cong_saket_code character(4) COLLATE pg_catalog."default",
    cong_saket_name character varying(35) COLLATE pg_catalog."default",
    cong_par_code character(4) COLLATE pg_catalog."default",
    cong_parish_name character varying(35) COLLATE pg_catalog."default",
    cong_code character(4) COLLATE pg_catalog."default",
    cong_name character varying(40) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.tbl_elc_struc1
(
    es_id integer NOT NULL,
    es_district character varying(30) COLLATE pg_catalog."default",
    es_circuit character varying(30) COLLATE pg_catalog."default",
    es_parish character varying(30) COLLATE pg_catalog."default",
    es_congregation character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT tbl_elc_struc1_pkey PRIMARY KEY (es_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_emergency_contact
(
    em_id integer NOT NULL,
    em_first_name character varying(30) COLLATE pg_catalog."default",
    em_surname character varying(30) COLLATE pg_catalog."default",
    em_phone character varying(25) COLLATE pg_catalog."default",
    em_email_address character varying(35) COLLATE pg_catalog."default",
    em_address character varying(60) COLLATE pg_catalog."default",
    em_ralation character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT tbl_mergency_contact_pkey PRIMARY KEY (em_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_pers_documents
(
    persdoc_id integer NOT NULL,
    persdoc_district boolean,
    persdoc_ordination boolean,
    persdoc_baprism boolean,
    persdoc_confirmation boolean,
    persdoc_marriage boolean,
    persdoc_divorce boolean,
    persdoc_police boolean,
    persdoc_nid boolean,
    persdoc_birth boolean,
    persdoc_passport boolean,
    persdoc_workpermit boolean,
    persdoc_diability boolean,
    persdoc_education boolean,
    persdoc_others character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tbl_pers_documents_pkey PRIMARY KEY (persdoc_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_person
(
    pers_id integer NOT NULL,
    pers_title character varying(25) COLLATE pg_catalog."default",
    pers_given_name character varying(25) COLLATE pg_catalog."default",
    pers_baptism_name character varying(25) COLLATE pg_catalog."default",
    pers_middle_name character varying(65) COLLATE pg_catalog."default",
    pers_surname character varying(25) COLLATE pg_catalog."default",
    pers_date_of_birth date,
    pers_height numeric(3, 0),
    pers_weight numeric(3, 0),
    pers_blood character varying(10) COLLATE pg_catalog."default",
    pers_eye_color character varying(25) COLLATE pg_catalog."default",
    pers_skincomplexion character varying(25) COLLATE pg_catalog."default",
    pers_nationality character varying(10) COLLATE pg_catalog."default" DEFAULT 'PNG'::character varying,
    pers_disabilitie character varying(25) COLLATE pg_catalog."default",
    pers_marital_status character varying(30) COLLATE pg_catalog."default",
    speaking_english numeric(1, 0),
    writing_english numeric(1, 0),
    speaking_tok_pisin numeric(1, 0),
    writing_tok_psin numeric(1, 0),
    speaking_jabem numeric(1, 0),
    writing_jabem numeric(1, 0),
    speaking_kotec numeric(1, 0),
    writing_kotec numeric(1, 0),
    speaking_notu numeric(1, 0),
    writing_notu numeric(1, 0),
    pers_spouse_id integer,
    pers_res_id integer,
    pers_created_at date DEFAULT now(),
    pers_admin_struc1 integer,
    pers_elc_struc1 integer,
    pers_school_id integer,
    pers_updated_at timestamp with time zone,
    per_marriage_regis numeric(4, 0),
    CONSTRAINT tbl_person_pkey PRIMARY KEY (pers_id),
    CONSTRAINT tbl_person_pers_admin_struc1_key UNIQUE (pers_admin_struc1),
    CONSTRAINT tbl_person_pers_elc_struc1_key UNIQUE (pers_elc_struc1),
    CONSTRAINT tbl_person_pers_res_id_key UNIQUE (pers_res_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_person_a
(
    ordnum integer NOT NULL,
    title character varying(25) COLLATE pg_catalog."default",
    first_nnme character varying(50) COLLATE pg_catalog."default",
    surnnme character varying(50) COLLATE pg_catalog."default",
    congregation character varying(50) COLLATE pg_catalog."default",
    theaddress character varying(65) COLLATE pg_catalog."default",
    city character varying(50) COLLATE pg_catalog."default",
    province character varying(25) COLLATE pg_catalog."default",
    phonenum numeric(13, 0),
    currdistrict character varying(50) COLLATE pg_catalog."default",
    pstatus numeric(1, 0),
    birthdate date,
    sex numeric(1, 0),
    asples character varying(25) COLLATE pg_catalog."default",
    asdistrict character varying(50) COLLATE pg_catalog."default",
    regnum numeric(5, 0),
    niugini_lutheran boolean,
    nasnum numeric(10, 0),
    edasuper numeric(10, 0),
    ord_y_n boolean,
    orddate date,
    ordplace character varying(50) COLLATE pg_catalog."default",
    mstatus numeric(1, 0),
    yrmarried numeric(4, 0),
    spouse_name character varying(30) COLLATE pg_catalog."default",
    spouse_work character varying(55) COLLATE pg_catalog."default",
    children character varying(50) COLLATE pg_catalog."default",
    hsname character varying(40) COLLATE pg_catalog."default",
    hs_date numeric(9, 0),
    seminary character varying(30) COLLATE pg_catalog."default",
    seminary_date numeric(9, 0),
    degree numeric(1, 0),
    created_at date DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT tbl_person_a_pkey PRIMARY KEY (ordnum)
);

CREATE TABLE IF NOT EXISTS public.tbl_residence
(
    res_address character varying(50) COLLATE pg_catalog."default",
    res_house character varying(25) COLLATE pg_catalog."default",
    res_email character varying(35) COLLATE pg_catalog."default",
    res_digicel character varying(30) COLLATE pg_catalog."default",
    res_bmobile character varying(30) COLLATE pg_catalog."default",
    res_vodafone character varying(30) COLLATE pg_catalog."default",
    res_social_media character varying(60) COLLATE pg_catalog."default",
    res_pers_id integer NOT NULL,
    CONSTRAINT tbl_residence_pkey PRIMARY KEY (res_pers_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_service_area
(
    svc_id integer NOT NULL,
    svc_order_id integer NOT NULL,
    svc_role character varying(80) COLLATE pg_catalog."default",
    svc_year_from numeric(4, 0),
    svc_year_to numeric(4, 0),
    svc_district character varying(40) COLLATE pg_catalog."default",
    svc_circuit character varying(40) COLLATE pg_catalog."default",
    svc_par_cong_inst character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT tbl_service_area_pkey PRIMARY KEY (svc_id, svc_order_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_spouse
(
    sp_id integer NOT NULL,
    sp_given_name character varying(25) COLLATE pg_catalog."default",
    sp_full_name character varying(25) COLLATE pg_catalog."default",
    sp_maiden_name character varying(25) COLLATE pg_catalog."default",
    sp_gender character varying(15) COLLATE pg_catalog."default",
    sp_birthdate date,
    sp_national character varying(15) COLLATE pg_catalog."default",
    sp_religion character varying(25) COLLATE pg_catalog."default",
    sp_denomination character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT tbl_spouse_pkey PRIMARY KEY (sp_id)
);

CREATE TABLE IF NOT EXISTS public.test
(
    name character varying(50) COLLATE pg_catalog."default",
    docu character varying(250)[] COLLATE pg_catalog."default",
    zahl numeric(4, 0)
);

ALTER TABLE IF EXISTS public.tbl_admin_struc1
    ADD CONSTRAINT tbl_admin_struc1_admin_id_fkey FOREIGN KEY (admin_id)
    REFERENCES public.tbl_person (pers_admin_struc1) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS tbl_admin_struc1_pkey
    ON public.tbl_admin_struc1(admin_id);


ALTER TABLE IF EXISTS public.tbl_banking
    ADD CONSTRAINT tbl_banking_ba_pers_id_fkey FOREIGN KEY (ba_pers_id)
    REFERENCES public.tbl_person (pers_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS tbl_banking_pkey
    ON public.tbl_banking(ba_pers_id);


ALTER TABLE IF EXISTS public.tbl_dep_pers_rel
    ADD CONSTRAINT tbl_dep_pers_rel_rel_dep_id_fkey FOREIGN KEY (rel_dep_id)
    REFERENCES public.tbl_dependants (dep_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_dep_pers_rel
    ADD CONSTRAINT tbl_dep_pers_rel_rel_pers_id_fkey FOREIGN KEY (rel_pers_id)
    REFERENCES public.tbl_person (pers_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_edu_other
    ADD CONSTRAINT tbl_edu_other_eo_id_fkey FOREIGN KEY (eo_id)
    REFERENCES public.tbl_person (pers_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_edu_school
    ADD CONSTRAINT tbl_edu_school_es_id_fkey FOREIGN KEY (es_id)
    REFERENCES public.tbl_person (pers_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_elc_struc1
    ADD CONSTRAINT tbl_elc_struc1_es_id_fkey FOREIGN KEY (es_id)
    REFERENCES public.tbl_person (pers_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS tbl_elc_struc1_pkey
    ON public.tbl_elc_struc1(es_id);


ALTER TABLE IF EXISTS public.tbl_emergency_contact
    ADD CONSTRAINT tbl_mergency_contact_em_id_fkey FOREIGN KEY (em_id)
    REFERENCES public.tbl_person (pers_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS tbl_mergency_contact_pkey
    ON public.tbl_emergency_contact(em_id);


ALTER TABLE IF EXISTS public.tbl_residence
    ADD CONSTRAINT tbl_residence_res_pers_id_fkey FOREIGN KEY (res_pers_id)
    REFERENCES public.tbl_person (pers_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS tbl_residence_pkey
    ON public.tbl_residence(res_pers_id);

END;