-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.congregation
(
    cong_id integer NOT NULL DEFAULT nextval('tbl_congregation_cong_id_seq'::regclass),
    cong_dist_id integer,
    cong_sek_id integer,
    cong_par_id integer,
    cong_code character(4) COLLATE pg_catalog."default",
    cong_name character varying(40) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.elc_district
(
    dis_id integer NOT NULL DEFAULT nextval('tbl_elc_district_dis_id_seq'::regclass),
    dist_code character(3) COLLATE pg_catalog."default" NOT NULL,
    dist_name character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tbl_elc_district_pkey PRIMARY KEY (dis_id)
);

CREATE TABLE IF NOT EXISTS public.elc_seket
(
    sek_id integer NOT NULL DEFAULT nextval('tbl_seket_sek_id_seq'::regclass),
    dist_id integer,
    sek_code character(3) COLLATE pg_catalog."default",
    sek_name character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT pk_tbl_sek PRIMARY KEY (sek_id)
);

CREATE TABLE IF NOT EXISTS public.hans
(
    datum date
);

CREATE TABLE IF NOT EXISTS public.pers_school_rel
(
    rel_pers_id integer NOT NULL,
    rel_sch_id integer NOT NULL,
    rel_order_nr integer NOT NULL,
    rel_year character varying COLLATE pg_catalog."default",
    rel_sch_certificate character varying COLLATE pg_catalog."default",
    CONSTRAINT pers_school_rel_pkey PRIMARY KEY (rel_sch_id, rel_pers_id)
);

CREATE TABLE IF NOT EXISTS public.person
(
    pers_given_name character varying(25) COLLATE pg_catalog."default",
    pers_baptism_name character varying(25) COLLATE pg_catalog."default",
    pers_middle_name character varying(65) COLLATE pg_catalog."default",
    pers_surname character varying(25) COLLATE pg_catalog."default",
    pers_date_of_birth date,
    pers_height numeric(3, 0),
    pers_weight numeric(3, 0),
    pers_blood character varying(10) COLLATE pg_catalog."default",
    pers_eye_color character varying(25) COLLATE pg_catalog."default",
    pers_skincomplexion character varying(25) COLLATE pg_catalog."default",
    pers_nationality character varying(10) COLLATE pg_catalog."default",
    pers_marital_status character varying(10) COLLATE pg_catalog."default",
    pers_id integer NOT NULL DEFAULT nextval('person_pers_id_seq'::regclass),
    pers_spouse_id integer,
    pers_created_at date,
    pers_updates_at date,
    pers_admin_id integer,
    speaking_english numeric(1, 0),
    writing_english numeric(1, 0),
    speaking_tok_pisin numeric(1, 0),
    writing_tok_psin numeric(1, 0),
    speaking_jabem numeric(1, 0),
    writing_jabem numeric(1, 0),
    speaking_kotec numeric(1, 0),
    writing_kotec numeric(1, 0),
    pers_title character varying(25) COLLATE pg_catalog."default",
    pers_diabilities character varying(40) COLLATE pg_catalog."default",
    pers_ward_id integer,
    pers_disabilitie character varying(25) COLLATE pg_catalog."default",
    pers_res_id integer,
    CONSTRAINT person_pkey PRIMARY KEY (pers_id),
    CONSTRAINT uidx_pes_spouse_id UNIQUE (pers_spouse_id)
);

CREATE TABLE IF NOT EXISTS public.residence
(
    res_address character varying(50) COLLATE pg_catalog."default",
    res_house character varying(25) COLLATE pg_catalog."default",
    res_email character varying(35) COLLATE pg_catalog."default",
    res_digicel character varying(30) COLLATE pg_catalog."default",
    res_bmobile character varying(30) COLLATE pg_catalog."default",
    res_vodafone character varying(30) COLLATE pg_catalog."default",
    res_social_media character varying(60) COLLATE pg_catalog."default",
    res_id integer NOT NULL DEFAULT nextval('residence_res_id_seq'::regclass),
    CONSTRAINT residence_pkey PRIMARY KEY (res_id)
);

CREATE TABLE IF NOT EXISTS public.school
(
    sch_name character varying(50) COLLATE pg_catalog."default",
    sch_id integer NOT NULL DEFAULT nextval('school_sch_id_seq'::regclass),
    CONSTRAINT "School_pkey" PRIMARY KEY (sch_id)
);

CREATE TABLE IF NOT EXISTS public.school
(
    sch_name character varying(50) COLLATE pg_catalog."default",
    sch_id integer NOT NULL DEFAULT nextval('school_sch_id_seq'::regclass),
    CONSTRAINT "School_pkey" PRIMARY KEY (sch_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_admin_structure
(
    admin_province character varying(40) COLLATE pg_catalog."default" NOT NULL,
    admin_district character varying(40) COLLATE pg_catalog."default" NOT NULL,
    admin_llg character varying(40) COLLATE pg_catalog."default" NOT NULL,
    admin_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT admin_structure_pkey PRIMARY KEY (admin_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_elc_cong_codes
(
    cong_id integer NOT NULL DEFAULT nextval('tbl_cong_codes_cong_id_seq'::regclass),
    cong_dist_code character(3) COLLATE pg_catalog."default",
    cong_dist_name character varying(35) COLLATE pg_catalog."default",
    cong_saket_code character(4) COLLATE pg_catalog."default",
    cong_saket_name character varying(35) COLLATE pg_catalog."default",
    cong_par_code character(4) COLLATE pg_catalog."default",
    cong_parish_name character varying(35) COLLATE pg_catalog."default",
    cong_code character(4) COLLATE pg_catalog."default",
    cong_name character varying(40) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.tbl_dep_pers_rel
(
    rel_pers_id integer NOT NULL,
    rel_dep_id integer NOT NULL,
    rel_order integer
);

CREATE TABLE IF NOT EXISTS public.tbl_dependants
(
    dep_id integer NOT NULL DEFAULT nextval('dependants_dep_id_seq'::regclass),
    dep_name character varying(25) COLLATE pg_catalog."default",
    dep_sex character(1) COLLATE pg_catalog."default",
    dep_dob character varying(15) COLLATE pg_catalog."default",
    dep_relation character varying(15) COLLATE pg_catalog."default",
    dep_diability character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT "Dependants_pkey" PRIMARY KEY (dep_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_elc_struc1
(
    es_id integer NOT NULL DEFAULT nextval('tbal_elc_struc1_es_id_seq'::regclass),
    es_district character varying(30) COLLATE pg_catalog."default",
    es_circuit character varying(30) COLLATE pg_catalog."default",
    es_parish character varying(30) COLLATE pg_catalog."default",
    es_congregation character varying(30) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.tbl_parish
(
    par_id integer NOT NULL DEFAULT nextval('tbl_parish_par_id_seq'::regclass),
    par_dist_id integer,
    par_sek_id integer,
    par_code character(4) COLLATE pg_catalog."default",
    par_name character varying(25) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.tbl_person
(
    pers_id integer NOT NULL DEFAULT nextval('tbl_person_pers_id_seq'::regclass),
    pers_title character varying(25) COLLATE pg_catalog."default",
    pers_given_name character varying(25) COLLATE pg_catalog."default",
    pers_baptism_name character varying(25) COLLATE pg_catalog."default",
    pers_middle_name character varying(65) COLLATE pg_catalog."default",
    pers_surname character varying(25) COLLATE pg_catalog."default",
    pers_date_of_birth date,
    pers_height numeric(3, 0),
    pers_weight numeric(3, 0),
    pers_blood character varying(10) COLLATE pg_catalog."default",
    pers_eye_color character varying(25) COLLATE pg_catalog."default",
    pers_skincomplexion character varying(25) COLLATE pg_catalog."default",
    pers_nationality character varying(10) COLLATE pg_catalog."default",
    pers_disabilitie character varying(25) COLLATE pg_catalog."default",
    pers_marital_status character varying(30) COLLATE pg_catalog."default",
    speaking_english numeric(1, 0),
    writing_english numeric(1, 0),
    speaking_tok_pisin numeric(1, 0),
    writing_tok_psin numeric(1, 0),
    speaking_jabem numeric(1, 0),
    writing_jabem numeric(1, 0),
    speaking_kotec numeric(1, 0),
    writing_kotec numeric(1, 0),
    speaking_notu numeric(1, 0),
    writing_notu numeric(1, 0),
    pers_spouse_id integer,
    pers_admin_id integer,
    pers_ward_id integer,
    pers_res_id integer,
    pers_created_at date DEFAULT now(),
    pers_updatet_at date DEFAULT now(),
    pers_elc_struc integer,
    CONSTRAINT tbl_person_pkey PRIMARY KEY (pers_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_service_area
(
    svc_id integer NOT NULL DEFAULT nextval('service_area_svc_id_seq'::regclass),
    svc_role character varying(80) COLLATE pg_catalog."default",
    svc_year character varying(20) COLLATE pg_catalog."default",
    svc_district character varying(40) COLLATE pg_catalog."default",
    svc_circuit character varying(40) COLLATE pg_catalog."default",
    svc_par_cong_inst character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT service_area_pkey PRIMARY KEY (svc_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_service_area
(
    svc_id integer NOT NULL DEFAULT nextval('service_area_svc_id_seq'::regclass),
    svc_role character varying(80) COLLATE pg_catalog."default",
    svc_year character varying(20) COLLATE pg_catalog."default",
    svc_district character varying(40) COLLATE pg_catalog."default",
    svc_circuit character varying(40) COLLATE pg_catalog."default",
    svc_par_cong_inst character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT service_area_pkey PRIMARY KEY (svc_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_spouse
(
    sp_id integer NOT NULL DEFAULT nextval('tbl_spouse_sp_id_seq'::regclass),
    sp_given_name character varying(25) COLLATE pg_catalog."default",
    sp_full_name character varying(25) COLLATE pg_catalog."default",
    sp_maiden_name character varying(25) COLLATE pg_catalog."default",
    sp_gender character varying(15) COLLATE pg_catalog."default",
    sp_birthdate date,
    sp_national character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT tbl_spouse_pkey PRIMARY KEY (sp_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_svc_pers_rel
(
    rel_svc_id integer,
    rel_pers_id integer,
    rel_order integer
);

CREATE TABLE IF NOT EXISTS public.tbl_spouse
(
    sp_id integer NOT NULL DEFAULT nextval('tbl_spouse_sp_id_seq'::regclass),
    sp_given_name character varying(25) COLLATE pg_catalog."default",
    sp_full_name character varying(25) COLLATE pg_catalog."default",
    sp_maiden_name character varying(25) COLLATE pg_catalog."default",
    sp_gender character varying(15) COLLATE pg_catalog."default",
    sp_birthdate date,
    sp_national character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT tbl_spouse_pkey PRIMARY KEY (sp_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_svc_pers_rel
(
    rel_svc_id integer,
    rel_pers_id integer,
    rel_order integer
);

CREATE TABLE IF NOT EXISTS public.ward
(
    wa_ward character varying(22) COLLATE pg_catalog."default",
    wa_village character varying(25) COLLATE pg_catalog."default",
    wa_tribe character varying(25) COLLATE pg_catalog."default",
    wa_clan character varying(25) COLLATE pg_catalog."default",
    wa_id integer NOT NULL DEFAULT nextval('ward_wa_id_seq1'::regclass),
    CONSTRAINT ward_pkey PRIMARY KEY (wa_id)
);
END;